version: "3"
services:
  db:
    image: postgres:14.4-bullseye
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tch_core_development
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  postgres-data:
